site2/bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site2/bboard/main/urls.py
from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile, profile_posts_add, profile_posts_delete
from .views import BBLogoutView
from .views import RegisterUserView, RegisterDoneView

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/login', BBLoginView.as_view(), name='login'),
    path('<str:page>/', other_page, name='other'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/add/', profile_posts_add, name='profile_posts_add'),
    path('accounts/profile/delete/<int:pk>', profile_posts_delete.as_view(), name='profile_posts_delete'),

]

site2/bboard/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path


class AdvUser(AbstractUser):
    fio = models.CharField(default=True, verbose_name='Введите ФИО', max_length=50)

    class Meta(AbstractUser.Meta):
        pass


class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название')

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'


class Posts(models.Model):
    CHOICES_STATUS = (
        ("Новый", 'Новый'),
        ("Принято в работу", 'Принято в работу'),
        ("Выполнено", 'Выполнено'),
        ("Отменено", 'Отменено'),
    )
    title = models.CharField(max_length=40, verbose_name='Название')
    description = models.TextField(max_length=100, verbose_name='Описание')
    category = models.ForeignKey(Category, max_length=120, on_delete=models.CASCADE, verbose_name='Категория')
    status = models.TextField(verbose_name='Статус заявки', choices=CHOICES_STATUS, default="Новый")
    cancellation = models.CharField(max_length=40, verbose_name='Введите если отменяете заказ', blank=True, null=True)
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор объявления')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    class Meta:
        verbose_name_plural = 'Заявки'
        verbose_name = 'Заявка'
        ordering = ['-created_at']


class AddCommentary(models.Model):
    bb = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Заявки')
    comment = models.CharField(max_length=64, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Комментарий'
        verbose_name = 'Комментарий'


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Заявки')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

site2/bboard/main/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import AdvUser, Posts, AdditionalImage
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator


class RegisterUserForm(forms.ModelForm):
    fio = forms.CharField(label='Ваше ФИО', required=True, widget=forms.TextInput,
                          validators=[RegexValidator('([А-ЯЁ][а-яё]+[\-\s]?){3,}', message='ФИО введено не верно')])
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')
    send_messages = forms.BooleanField(label='Поставьте галочку', required=True)

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'fio', 'password1', 'password2',
                  'send_messages')


def file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('Файл слишком большой. Размер файла не должен превышать 2 МБ.')


class PostsForm(forms.ModelForm):
    image = forms.FileField(validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp']), file_size],
                            label='Фотография', )
    class Meta:
        model = Posts
        fields = '__all__'
        widgets = {'author': forms.HiddenInput, 'status': forms.HiddenInput}
AIFormSet = inlineformset_factory(Posts, AdditionalImage, fields='__all__')


class FilterForm(forms.Form):
    CHOICES_STATUS = (
        ("о", 'Все'),
        ("Новый", 'Новый'),
        ("Принято в работу", 'Принято в работу'),
        ("Выполнено", 'Выполнено'),
        ("Отменено", 'Отменено'),
    )
    keyword = forms.ChoiceField(choices=CHOICES_STATUS, label='Фильтр')


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')


class BbAdminForm(forms.ModelForm):
    def clean(self):
       status = self.cleaned_data['status']
       if (self.instance.status != status) and status == 'Новая':
           raise ValidationError("Вы не можете поменять статус на новая")
       if (self.instance.status == 'Выполнено'):
           raise ValidationError("Вы не можете поменять статус с Выполнено")
       if (self.instance.status == 'Принято в работу'):
           raise ValidationError("Вы не можете поменять статус с Принято в работу")
       if (self.instance.status == 'Отменено'):
           raise ValidationError("Вы не можете поменять статус с отменено")

site2/bboard/main/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import AdvUser, Posts
from django.views.generic import CreateView
from .forms import RegisterUserForm, PostsForm
from django.views.generic.base import TemplateView
from django.views.generic import DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import FilterForm
from django.db.models import Q


def index(request):
    bbs = Posts.objects.filter(status='Выполнено').order_by('-created_at')[:4]
    count = Posts.objects.filter(status='Принято в работу').count()
    context = {'bb': bbs, 'count': count}
    return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    post_all = Posts.objects.all()
    if request.user.is_staff:
        posts = Posts.objects.filter()
    else:
        posts = Posts.objects.filter(author=request.user.pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(status__icontains=keyword)
        posts = posts.filter(q)
    else:
        keyword = ''
    form = FilterForm(initial={'keyword': keyword})
    context = {'posts': posts, 'form': form}
    return render(request, 'main/profile.html', context)


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


@login_required
def profile_posts_add(request):
    if request.method == 'POST':
        form = PostsForm(request.POST, request.FILES)
        if form.is_valid():
            posts = form.save()
            return redirect('main:profile')
    else:
        form = PostsForm(initial={'author': request.user.pk})
    context = {'form': form}
    return render(request, 'main/posts_add.html', context)


class profile_posts_delete(SuccessMessageMixin, DeleteView):
    model = Posts
    template_name = 'main/posts_delete.html'
    success_url = '/accounts/profile/'
    success_message = "Объявление удалено"

site2/bboard/main/templates/main/index.html
{% extends "layout/base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="content">
    <div class="title">
        <h1>Последние выполненные заказы</h1>
    </div>
    <div> В работе: {{ count }}</div>
    <form class="col-md-auto form-inline text-white">

    </form>
    {% for post in bb %}
    <div class="adds">
        <div class="pic">
            <img src="{{MEDIA_URL}}{{ post.image.url }}">
        </div>
        <div class="text">
            <div class="name"> Название: {{post.title}}</div>
            <div class="time">Дата добавления: {{post.created_at}}</div>
            <div class="description">Описание: {{post.description}}</div>
            <div class="condition">Статус:<p> {{post.status}}</p></div>
            <div class="category">Категория: <p>{{post.category}}</p></div>
            <div> {{post.author}}</div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

site2/bboard/main/templates/main/login.html
{% extends 'layout/base.html' %} &nbsp;{% block content %}
<form method="post">
  {% csrf_token %}
  <div class="login-box">
    <h2>Войти</h2>
    <form>
        <div class="user-box">
            <input type="text" name="username" required="">
            <label>Имя</label>
        </div>
        <div class="user-box">
            <input type="password" name="password" required="">
            <label>Пароль</label>
        </div>
       <button type="submit">Войти</button>
    </form>
</div>
</form>
{% endblock content %}

site2/bboard/main/templates/main/logout.html
{% extends "layout/base.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
<div class="clear">
    <div class="logout">
        <h2>Выход</h2>
        <p>Вы успешно вышли с сайта.</p>
    </div>
</div>
{% endblock %}

site2/bboard/main/templates/main/post.html
{% extends "layout/base.html" %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<h1>Посты</h1>
{% for post in posts %}
 <p>
     {{post.title}}
 </p>
{% endfor %}
{% endblock %}

site2/bboard/main/templates/main/posts_add.html
{% extends "layout/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %} Добавление заявки {% endblock %}

{% block content %}
<h2 class="text-white">Создать заявку</h2>
<form class="text-white" method="post" enctype="multipart/form-data">
    <div class="block-content">
        {% csrf_token %}
        <div class="form-app">{% bootstrap_form form layout='horizontal' %}</div>
        <div class="button">{% buttons submit='Добавить' %} {% endbuttons %}</div>
    </div>
</form>
{% endblock %}

site2/bboard/main/templates/main/posts_delete.html
{% extends "layout/base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}
<div class="clear">
    <div class="logout">
        <h1>Удаление заявки</h1>
        <form method="post">
            {% csrf_token %}
            <p><input type="submit" value="Удалить"></p>
        </form>
    </div>
</div>
{% endblock %}

site2/bboard/main/templates/main/profile.html
{% extends "layout/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<div class="content">
    <h2>Профиль пользователя {{ user.username }}</h2>
    <h2>Здравствуйте, {{ user.fio }} </h2>
    <form class="filter">
        {% bootstrap_form form %}
        {% bootstrap_button content='Фильтровать' button_type='submit' %}
    </form>
    {% for post in posts %}
    <div class="adds">
        <div class="pic">
            <img src="{{MEDIA_URL}}{{ post.image.url }}">
        </div>
        <div class="text">
            <div class="name"> Название: {{post.title}}</div>
            <div class="time">Дата добавления: {{post.created_at}}</div>
            <div class="description">Описание: {{post.description}}</div>
            <div class="condition">Статус:<p> {{post.status}}</p></div>
            {% if post.cancellation %}
            <div class="description">Причина отмены:{{ post.cancellation }}</div>
            {% endif %}
            <div class="category">Категория: <p>{{post.category}}</p></div>
            <div> {{post.author}}</div>
            <div><a href="{% url 'main:profile_posts_delete' post.id %}">Удалить</a></div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}

site2/bboard/main/templates/main/register.html
{% extends 'layout/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="reg-box">
    <h2>Регистрация</h2>
    <form action="." method="post">
       {% csrf_token %}
        <div class="user-box">
            <input type="text" name="fio" required="">
            <label>ФИО</label>
        </div>
        <div class="user-box">
            <input type="text" name="username" required="">
            <label>Логин</label>
        </div>
        <div class="user-box">
            <input type="email" name="email" required="">
            <label>Почта</label>
        </div>
        <div class="user-box">
            <input type="password" name="password1" required="">
            <label>Пароль</label>
        </div>
        <div class="user-box">
            <input type="password" name="password2" required="">
            <label>Повторите пароль</label>
        </div>
        <div>
            <label>Обработка персональных данных</label>
            <input type="checkbox" name="send_messages">
        </div>
        <button type="submit">Отправить</button>
    </form>
</div>
{% endblock %}

site2/bboard/main/templates/main/register_done.html
{% extends 'layout/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="clear">
    <div class="logout">
        <h2>Welcome {{new_user.first_name}}!</h2>
        <a href="{% url 'main:login' %}">Login</a>
    </div>
</div>
{% endblock %}